/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as CabanasIndexRouteImport } from './routes/cabanas.index'
import { Route as CabanasSlugRouteImport } from './routes/cabanas.$slug'
import { Route as ReservaSucessoRouteImport } from './routes/reserva.sucesso'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const CabanasIndexRoute = CabanasIndexRouteImport.update({
  id: '/cabanas/',
  path: '/cabanas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabanasSlugRoute = CabanasSlugRouteImport.update({
  id: '/cabanas/$slug',
  path: '/cabanas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaSucessoRoute = ReservaSucessoRouteImport.update({
  id: '/reserva/sucesso',
  path: '/reserva/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/reserva/sucesso': typeof ReservaSucessoRoute
  '/cabanas/': typeof CabanasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/reserva/sucesso': typeof ReservaSucessoRoute
  '/cabanas': typeof CabanasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/reserva/sucesso': typeof ReservaSucessoRoute
  '/cabanas/': typeof CabanasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/experiencia'
    | '/cabanas/$slug'
    | '/reserva/sucesso'
    | '/cabanas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/experiencia'
    | '/cabanas/$slug'
    | '/reserva/sucesso'
    | '/cabanas'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/experiencia'
    | '/cabanas/$slug'
    | '/reserva/sucesso'
    | '/cabanas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  ExperienciaRoute: typeof ExperienciaRoute
  CabanasSlugRoute: typeof CabanasSlugRoute
  ReservaSucessoRoute: typeof ReservaSucessoRoute
  CabanasIndexRoute: typeof CabanasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabanas/': {
      id: '/cabanas/'
      path: '/cabanas'
      fullPath: '/cabanas/'
      preLoaderRoute: typeof CabanasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabanas/$slug': {
      id: '/cabanas/$slug'
      path: '/cabanas/$slug'
      fullPath: '/cabanas/$slug'
      preLoaderRoute: typeof CabanasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/sucesso': {
      id: '/reserva/sucesso'
      path: '/reserva/sucesso'
      fullPath: '/reserva/sucesso'
      preLoaderRoute: typeof ReservaSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  ExperienciaRoute: ExperienciaRoute,
  CabanasSlugRoute: CabanasSlugRoute,
  ReservaSucessoRoute: ReservaSucessoRoute,
  CabanasIndexRoute: CabanasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
