/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ExperienciaRouteImport } from './routes/experiencia'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as CabanasIndexRouteImport } from './routes/cabanas.index'
import { Route as CabanasSlugRouteImport } from './routes/cabanas.$slug'
import { Route as ReservaSucessoRouteImport } from './routes/reserva.sucesso'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienciaRoute = ExperienciaRouteImport.update({
  id: '/experiencia',
  path: '/experiencia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CabanasIndexRoute = CabanasIndexRouteImport.update({
  id: '/cabanas/',
  path: '/cabanas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabanasSlugRoute = CabanasSlugRouteImport.update({
  id: '/cabanas/$slug',
  path: '/cabanas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservaSucessoRoute = ReservaSucessoRouteImport.update({
  id: '/reserva/sucesso',
  path: '/reserva/sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/reserva/sucesso': typeof ReservaSucessoRoute
  '/cabanas/': typeof CabanasIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/reserva/sucesso': typeof ReservaSucessoRoute
  '/cabanas': typeof CabanasIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contato': typeof ContatoRoute
  '/experiencia': typeof ExperienciaRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/reserva/sucesso': typeof ReservaSucessoRoute
  '/cabanas/': typeof CabanasIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contato'
    | '/experiencia'
    | '/admin'
    | '/cabanas/$slug'
    | '/reserva/sucesso'
    | '/cabanas/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contato'
    | '/experiencia'
    | '/cabanas/$slug'
    | '/reserva/sucesso'
    | '/cabanas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contato'
    | '/experiencia'
    | '/_authenticated/admin'
    | '/cabanas/$slug'
    | '/reserva/sucesso'
    | '/cabanas/'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContatoRoute: typeof ContatoRoute
  ExperienciaRoute: typeof ExperienciaRoute
  CabanasSlugRoute: typeof CabanasSlugRoute
  ReservaSucessoRoute: typeof ReservaSucessoRoute
  CabanasIndexRoute: typeof CabanasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experiencia': {
      id: '/experiencia'
      path: '/experiencia'
      fullPath: '/experiencia'
      preLoaderRoute: typeof ExperienciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/cabanas/': {
      id: '/cabanas/'
      path: '/cabanas'
      fullPath: '/cabanas/'
      preLoaderRoute: typeof CabanasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabanas/$slug': {
      id: '/cabanas/$slug'
      path: '/cabanas/$slug'
      fullPath: '/cabanas/$slug'
      preLoaderRoute: typeof CabanasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserva/sucesso': {
      id: '/reserva/sucesso'
      path: '/reserva/sucesso'
      fullPath: '/reserva/sucesso'
      preLoaderRoute: typeof ReservaSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContatoRoute: ContatoRoute,
  ExperienciaRoute: ExperienciaRoute,
  CabanasSlugRoute: CabanasSlugRoute,
  ReservaSucessoRoute: ReservaSucessoRoute,
  CabanasIndexRoute: CabanasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
