/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CabanasIndexRouteImport } from './routes/cabanas.index'
import { Route as CabanasSlugRouteImport } from './routes/cabanas.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabanasIndexRoute = CabanasIndexRouteImport.update({
  id: '/cabanas/',
  path: '/cabanas/',
  getParentRoute: () => rootRouteImport,
} as any)
const CabanasSlugRoute = CabanasSlugRouteImport.update({
  id: '/cabanas/$slug',
  path: '/cabanas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/cabanas/': typeof CabanasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/cabanas': typeof CabanasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cabanas/$slug': typeof CabanasSlugRoute
  '/cabanas/': typeof CabanasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cabanas/$slug' | '/cabanas/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cabanas/$slug' | '/cabanas'
  id: '__root__' | '/' | '/cabanas/$slug' | '/cabanas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CabanasSlugRoute: typeof CabanasSlugRoute
  CabanasIndexRoute: typeof CabanasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabanas/': {
      id: '/cabanas/'
      path: '/cabanas'
      fullPath: '/cabanas/'
      preLoaderRoute: typeof CabanasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cabanas/$slug': {
      id: '/cabanas/$slug'
      path: '/cabanas/$slug'
      fullPath: '/cabanas/$slug'
      preLoaderRoute: typeof CabanasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CabanasSlugRoute: CabanasSlugRoute,
  CabanasIndexRoute: CabanasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
